### ISSUE TITLE
Running multiple shard

### ISSUE THREAD

**Issue by BlueskyFR** [screepers/screeps-launcher#25]
As stated at the end of [this](https://blog.screeps.com/2017/08/shards/) page, the world shards are supported on the private server.
How may I enable this feature?

Thanks in advance!

**Comment by ags131** [comment]
That is beyond the scope of this project, this is just a launcher. Shards are much more complicated to implement and requires extensive rewrites of the backend section.

**Comment by BlueskyFR** [comment]
@ags131 do you mean that the official shard handling system code has not been published to private servers?

**Comment by ags131** [comment]
Best bet would probably be to help on the xxscreeps project, since it has
sharding builtin. Otherwise, its complicated, would need to
essential rewrite backend-local to support hitting multiple dbs.
