### ISSUE TITLE
Enable pixels in the market

### ISSUE THREAD

**Issue by BlueskyFR** [screepers/screeps-launcher#26]
Hi! It seems that the pixels are not available by default, even after installing screepsmod-market.
How may I procede?

**Comment by ags131** [comment]
That is beyond the scope of this project, this is just a launcher. Market stuff is part of the market mods. Pixels are not fully implemented in private servers and would require a more extensive mod to enable inventory.

**Comment by BlueskyFR** [comment]
@ags131 would you know how I can help on this?
