### ISSUE TITLE
command arguments missing

### ISSUE THREAD

**Issue by Marcel-a** [screepers/screeps-launcher#3]
I think, there is a mistake in screeps-launcher/cmd/screeps-launcher/main.go
I cannot call `screeps-launcher` without any parameter to start the server. In line 19 you are accessing `os.Args[1]` but if you don't give any parameter, the array-element 1 dosn't exist. 
In the consoel I'm getting the following error:

> ~/screeps-launcher$ sudo ./screeps-launcher
> panic: runtime error: index out of range
>
>goroutine 1 [running]:
>main.main()
>        /home/circleci/project/cmd/screeps-launcher/main.go:19 +0x1cd

**Comment by ags131** [comment]
Was definitely a mistake there, that is now fixed, thanks!
