### ISSUE TITLE
Docker-Compose not working.

### ISSUE THREAD

**Issue by Smallinger** [screepers/screeps-launcher#31]
Hey with the latest Docker-Compose version i got this error.

```
2022/11/12 05:21:19 Installing Node
2022/11/12 05:21:19 Downloading https://nodejs.org/dist/v12.22.12/node-v12.22.12-linux-x64.tar.gz...
2022/11/12 05:21:19   200 OK
2022/11/12 05:21:19   downloaded 0/23131523 bytes (0.00%)
2022/11/12 05:21:19 Download failed: open node-v12.22.12-linux-x64.tar.gz: permission denied
2022/11/12 05:21:19 node-v12.22.12-linux-x64.tar.gz
2022/11/12 05:21:19 node-v12.22.12-linux-x64
2022/11/12 05:21:19 rename deps/node-v12.22.12-linux-x64 deps/node: no such file or directory
```

**Comment by bkconrad** [comment]
The docker container isn't able to write to the mounted volume. To make it readable, the simplest solution is to do something like:

`chmod 0777 /path/to/your/screeps-data`

More correctly you can set the owner for your data directory to uid 1000 to match what the container runs under but let's be real this is a private server for a dead game so just do 0777 and move on with your life.
