### ISSUE TITLE
how to configure map-tool user and password ?

### ISSUE THREAD

**Issue by stygmate** [screepers/screeps-launcher#7]
I have tried adding env variable MAPTOOL_USER and MAPTOOL_PASS in docker-compose env and in config.yml env -> common.
or at least how to get console output from map-tool at server launch ? (normally it print a generated password for user "admin")

**Comment by ags131** [comment]
The config.yml path is actually env -> shared, I've updated the sample to reflect that.
Either method should work, adding via config.yml or via `environment` in the docker-compose.yml
The output is in `logs/backend.log`, if a password is set via env variable, it will skip the generated password.

**Comment by stygmate** [comment]
thank you ! it work !
