### ISSUE TITLE
Unable to install on WIndows 10 Possible Dependency problems

### ISSUE THREAD

**Issue by ryu777mtg** [screepers/screeps-launcher#9]
I've tried to install using the screeps-launcher_v1.9.5_windows_amd64.exe to install on Windows 10 x64 system. I'm not sure if having an already installed version of NodeJS leads to the problem considering this is bundle with a version of NodeJS already. To me it seems like it sets up it's own environment to install everything you need so I doubt that is the problem which leads me to think there is something wrong and refuses to install all the way through. 

Here is the output from using CMD.exe in Adminstrative mode to install it via Command Line
[Click here for the output](https://pastebin.com/anhfau9u) <- Provide via pastebin.com

Any information regarding the issue or how to resolve it would be nice thank you for your time if you decide to look into the matter as NPM installs are getting to be annoying and was hopping this tool would work for me.

**Comment by OriginalPoster** [comment]
I am getting the same issue! Did you have any luck resolving this problem?

**Comment by OriginalPoster** [comment]
Nevermind? Mine just randomly started working??

**Comment by ryu777mtg** [comment]
If anyone else if having this issue I've finally figured that in order to get it to work is:
Step 1: I grabbed the newest nodejs from their site when launching the installer near the end click the check box to install chocolatey it will install build tools that work
Step 2: I grabbed the official Python 2 installer from their site when installing it make sure to have everything run from your machine this will install the path/environmental values
Step 3: May or may not be needed I uninstalled Python 3 from machine
Step 4: Download the Screeps Launcher then create and setup a config.yml in the same directory as the Screeps Launcher
Step 5: Right Click the Screeps Launcher and run as Administrator

All those steps seem to have gotten it to run smoothly with no problems.

This issue may be closed but I do recommend that others test this and maybe have this in the documentation for setting up for Windows.
